apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: {{ .Values.namespace}}
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: {{.Values.deployments.replicaCount}}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: {{ .Values.images.service1.name }}
        image: "{{.Values.images.apiGateway.repository}}:{{.Values.images.apiGateway.tag}}"
        imagePullPolicy: {{.Values.images.pullPolicy}}
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        env:
        - name: NODE_ENV
          value: dev_from_k8
        - name: service_1_service_name
          valueFrom: 
            configMapKeyRef:
              name: api-ingress-config-map
              key: service_1_service_name
        - name: service_2_service_name
          valueFrom: 
            configMapKeyRef:
              name: api-ingress-config-map
              key: service_2_service_name
