apiVersion: v1
kind: Service
metadata:
  name: service-1-service
  namespace:  {{ .Values.namespace}}
spec:
  selector:
    app: service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000