apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-1-deployment
  namespace: test-namespace
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-1-deployment
  targetCPUUtilizationPercentage: 10