apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-deployment
  namespace: test-namespace
  labels:
    app: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: latest/service-1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: dev_from_k8_service_1
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secret
        #       key: mongo-root-username
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secret
        #       key: mongo-root-password

