apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-deployment
  namespace: test-namespace
  labels:
    app: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: service-1/v3
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: dev_from_k8_service_1

